name: kokoro-tts
services:
  kokoro-tts:
    build:
      context: ../..
      dockerfile: docker/gpu/Dockerfile
    volumes:
      - ../../api/src:/app/api/src  # Mount src for development
    ports:
      - "8880:8880"
    environment:
      - PYTHONPATH=/app:/app/Kokoro-82M
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Gradio UI service
  gradio-ui:
    # image: ghcr.io/remsky/kokoro-fastapi-ui:latest
    # Uncomment below to build from source instead of using the released image
    build:
      context: ../../ui
    ports:
      - "7860:7860"
    volumes:
      - ../../ui/data:/app/ui/data
      - ../../ui/app.py:/app/app.py  # Mount app.py for hot reload
    environment:
      - GRADIO_WATCH=1  # Enable hot reloading
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
      - DISABLE_LOCAL_SAVING=false  # Set to 'true' to disable local saving and hide file view
