# README Configuration
# version is now automatically loaded from the VERSION file
tests_passed: "69"
coverage: "52"
kokoro_version: "0.7.9"
kokoro_commit: "31a2b63"
misaki_version: "0.7.9"
misaki_commit: "ebc76c2"
model_version: "1.0"
model_commit: "9901c2b"
model_commit_full: "9901c2b79161b6e898b7ea857ae5298f47b8b0d6"
