name: CI

on:
  push:
    branches: [ "core/uv-management" ]
  pull_request:
    branches: [ "core/uv-management" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: 1
    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Lint with ruff
      run: |
        uv run ruff check .

    - name: Test API and UI
      run: |
        uv run pytest api/tests/ ui/tests/ --asyncio-mode=auto --cov=api --cov=ui --cov-report=term-missing
