name: Docker Build and Publish

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build script
        run: |
          chmod +x docker/build.sh
          VERSION=$(cat VERSION)
          docker/build.sh $VERSION

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          IS_PRERELEASE: ${{ contains(github.ref, '-pre') }}
        with:
          generate_release_notes: true
          draft: true
          prerelease: ${{ contains(github.ref, '-pre') }}
